backend_users:
  label: Backend users
  manage:
    form: ~/modules/backend/models/user/fields.yaml
  view:
    toolbarButtons: link|unlink
    list: ~/modules/backend/models/user/columns.yaml

users:
  label: Users
  manage:
    form: $/rainlab/user/models/user/fields.yaml
    recordsPerPage: 50
  view:
    toolbarButtons: link|unlink
    recordUrl: rainlab/user/users/preview/:id
    list: $/rainlab/user/models/user/columns.yaml

features:
  label: Features
  manage:
    form: $/codecycler/teams/models/feature/fields.yaml
  view:
    toolbarButtons: link|unlink
    recordUrl: codecycler/teams/features/preview/:id
    list: $/codecycler/teams/models/feature/columns.yaml